zeroTrue: &zeroTrue
  score: 0
  countWords: true
zeroFalse: &zeroFalse
  score: 0
  countWords: false
oneTrue: &oneTrue
  score: 1
  countWords: true
oneFalse: &oneFalse
  score: 1
  countWords: false
tcrHtmlConfig: &tcrHtmlConfig
  a: *oneTrue
  code: *oneFalse
  img: *oneFalse
  h1: *oneTrue
  h2: *oneTrue
  h3: *oneTrue
  h4: *oneTrue
  h5: *oneTrue
  h6: *oneTrue
  br: *zeroTrue
  p: *zeroTrue
  em: *zeroTrue
  ul: *zeroTrue
  td: *zeroTrue
  hr: *zeroTrue
  ol: *zeroTrue
  pre: *zeroFalse
  strong: *zeroFalse
  blockquote: *zeroFalse
  li:
    score: 0.1
    countWords: true
allRoles: &allRoles
  - collaborator
  - contributor
collaboratorOnly: &collaboratorOnly
  - collaborator
teamMembersOnly: &teamMembersOnly
  - COLLABORATOR
  - OWNER
  - MEMBER
  - ADMIN
timeLabels: &timeLabels
  - name: "Time: <15 Minutes"
  - name: "Time: <1 Hour"
  - name: "Time: <2 Hours"
  - name: "Time: <4 Hours"
  - name: "Time: <1 Day"
  - name: "Time: <1 Week"
priorityLabels: &priorityLabels
  - name: "Priority: 0 (Regression)"
  - name: "Priority: 1 (Normal)"
  - name: "Priority: 2 (Medium)"
  - name: "Priority: 3 (High)"
  - name: "Priority: 4 (Urgent)"
  - name: "Priority: 5 (Emergency)"
plugins:
  - uses:
      - plugin: https://command-start-stop-main.deno.dev
        with:
          reviewDelayTolerance: 3 Days
          taskStaleTimeoutDuration: 30 Days
          startRequiresWallet: true
          maxConcurrentTasks:
            collaborator: 2
            contributor: 2
          emptyWalletText: Please set your wallet address with the /wallet command first and try again.
          rolesWithReviewAuthority: *teamMembersOnly
          requiredLabelsToStart:
            - name: "Priority: 0 (Regression)"
              allowedRoles: *allRoles
            - name: "Priority: 1 (Normal)"
              allowedRoles: *allRoles
            - name: "Priority: 2 (Medium)"
              allowedRoles: *allRoles
            - name: "Priority: 3 (High)"
              allowedRoles: *collaboratorOnly
            - name: "Priority: 4 (Urgent)"
              allowedRoles: *collaboratorOnly
            - name: "Priority: 5 (Emergency)"
              allowedRoles: *collaboratorOnly
          taskAccessControl:
            usdPriceMax:
              contributor: -1
              collaborator: Infinity

  - uses:
      - plugin: https://command-wallet-main.deno.dev
        with:
          registerWalletWithVerification: false
  - uses:
      - plugin: ubiquity-os-marketplace/command-ask@main
        with:
          model: deepseek/deepseek-r1-0528:free
          openAiBaseUrl: https://openrouter.ai/api/v1
  - uses:
      - plugin: https://command-query-main.deno.dev
        with:
          allowPublicQuery: true
  - uses:
      - plugin: https://daemon-pricing-main.deno.dev
        with:
          labels:
            time: *timeLabels
            priority: *priorityLabels
          basePriceMultiplier: 2
          shouldFundContributorClosedIssue: false
  - uses:
      - plugin: ubiquity-os-marketplace/text-conversation-rewards@main
        with:
          rewards:
            evmNetworkId: 100
            evmPrivateEncrypted: bd5AFnSCO6c5jJyPifpOfr5Zys29RE7SyXkEU3akT13RtGmYDrqGIGuvJQyH53HA5dIba7PL5bXfll0JebmwXYe5gHIXSGX80WuGMDHh0cFfeGjHhmUXe8kkZ1OT2De9qRpqejJcEzdfi-8XNAvP7cQu2Vt-7RNnPw
          incentives:
            contentEvaluator:
              enabled: true
              openAi:
                endpoint: https://openrouter.ai/api/v1
                model: google/gemini-2.5-flash
              multipliers:
                - role:
                    - ISSUE_SPECIFICATION
                  relevance: 1
            externalContent:
              llmImageModel:
                model: openai/gpt-4o
              llmWebsiteModel:
                model: google/gemini-2.5-flash
            userExtractor:
              redeemTask: true
            dataPurge:
              enabled: true
            formattingEvaluator:
              multipliers:
                - role:
                    - ISSUE_SPECIFICATION
                    - ISSUE_AUTHOR
                    - ISSUE_COLLABORATOR
                    - PULL_COLLABORATOR
                  multiplier: 1
                  rewards:
                    wordValue: 0.1
                    html: *tcrHtmlConfig
                - role:
                    - ISSUE_CONTRIBUTOR
                    - ISSUE_ASSIGNEE
                  multiplier: 0.25
                  rewards:
                    wordValue: 0.1
                    html: *tcrHtmlConfig
                - role:
                    - PULL_AUTHOR
                    - PULL_CONTRIBUTOR
                    - PULL_ASSIGNEE
                    - PULL_SPECIFICATION
                  multiplier: 0
                  rewards:
                    wordValue: 0
                    html: *tcrHtmlConfig
            permitGeneration: {}
            simplificationIncentivizer: {}
            payment: 
              automaticTransferMode: false
            reviewIncentivizer: {}
            githubComment:
              post: true
              debug: false
  - skipBotEvents: false
    uses:
      - plugin: ubiquity-os-marketplace/daemon-disqualifier@main
        with:
          warning: 7 days
          pullRequestRequired: true
          eventWhitelist:
            - pull_request.review_requested
            - pull_request.ready_for_review
            - pull_request_review_comment.created
            - issue_comment.created
            - push
          disqualification: 14 days
  - uses:
      - plugin: ubiquity-os-marketplace/daemon-merging@main
        with:
          approvalsRequired:
            collaborator: 1
            contributor: 2
          mergeTimeout:
            collaborator: 3.5 days
            contributor: 7 days
          repos:
            monitor: []
            ignore:
              - ubiquibot
              - launch-party
              - staging
              - production
          allowedReviewerRoles:
            - COLLABORATOR
            - MEMBER
            - OWNER
  - uses:
      - plugin: ubiquity-os-marketplace/text-vector-embeddings@main
        with:
          matchThreshold: 0.95
          warningThreshold: 0.75
          jobMatchingThreshold: 0.75
          alwaysRecommend: 0          
  - uses:
      - plugin: ubiquity-os-marketplace/daemon-pull-review@main
        with:
          openRouterAiModel: google/gemini-2.5-flash
          openRouterBaseUrl: https://openrouter.ai/api/v1
          tokenLimit:
            context: 200000
            completion: 4096
  - uses:
      - plugin: https://command-config-main.deno.dev
  - uses:
      - plugin: ubiquity-os-marketplace/personal-agent-bridge@main