plugins:
  - uses:
      - plugin: "https://ubiquity-os-command-start-stop-main.ubiquity.workers.dev"
  - uses:
      - plugin: "https://ubiquity-os-command-wallet-main.ubiquity.workers.dev"
  - uses:
      - plugin: "ubiquity-os-marketplace/command-ask@main"
  - uses:
      - plugin: "https://ubiquity-os-command-query-user-main.ubiquity.workers.dev"
  - uses:
      - plugin: "https://ubiquity-os-daemon-pricing-main.ubiquity.workers.dev"
  - uses:
      - plugin: "ubiquity-os-marketplace/text-conversation-rewards@main"
        with:
          evmPrivateEncrypted: "Y3TLzcTGk0mSyzJ5gHaUH1NzBGOwMVnhIEicX1QWQUEHR174JN9jo_3lC_7WXciY8VzZTw3-KQsXU9Bd60P07CLXUQd0fFvR5MbjE5s4XLywj6Uufv7GmibddoYNKuvL23VcDrRCddY0c6LxcmfILhnkKAk"
          evmNetworkId: 10
  - uses:
      - plugin: "ubiquity-os-marketplace/daemon-disqualifier@main"
  - uses:
      - plugin: "ubiquity-os-marketplace/daemon-merging@main"
  - uses:
      - plugin: "https://ubiquity-os-comment-vector-embeddings-main.ubiquity.workers.dev"
