zeroTrue: &zeroTrue
  score: 0
  countWords: true
zeroFalse: &zeroFalse
  score: 0
  countWords: false
oneTrue: &oneTrue
  score: 1
  countWords: true
oneFalse: &oneFalse
  score: 1
  countWords: false
tcrHtmlConfig: &tcrHtmlConfig
  a: *oneTrue
  code: *oneFalse
  img: *oneFalse
  h1: *oneTrue
  h2: *oneTrue
  h3: *oneTrue
  h4: *oneTrue
  h5: *oneTrue
  h6: *oneTrue
  br: *zeroTrue
  p: *zeroTrue
  em: *zeroTrue
  ul: *zeroTrue
  td: *zeroTrue
  hr: *zeroTrue
  ol: *zeroTrue
  pre: *zeroFalse
  strong: *zeroFalse
  blockquote: *zeroFalse
  li:
    score: 0.1
    countWords: true
allRoles: &allRoles
  - collaborator
  - contributor
collaboratorOnly: &collaboratorOnly
  - collaborator
teamMembersOnly: &teamMembersOnly
  - COLLABORATOR
  - OWNER
  - MEMBER
  - ADMIN
timeLabels: &timeLabels
  - name: "Time: <15 Minutes"
    collaboratorOnly: false
  - name: "Time: <1 Hour"
    collaboratorOnly: false
  - name: "Time: <2 Hours"
    collaboratorOnly: false
  - name: "Time: <4 Hours"
    collaboratorOnly: false
  - name: "Time: <1 Day"
    collaboratorOnly: false
  - name: "Time: <1 Week"
    collaboratorOnly: false
priorityLabels: &priorityLabels
  - name: "Priority: 0 (Regression)"
    collaboratorOnly: false
  - name: "Priority: 1 (Normal)"
    collaboratorOnly: false
  - name: "Priority: 2 (Medium)"
    collaboratorOnly: false
  - name: "Priority: 3 (High)"
    collaboratorOnly: false
  - name: "Priority: 4 (Urgent)"
    collaboratorOnly: false
  - name: "Priority: 5 (Emergency)"
    collaboratorOnly: false
plugins:
  ubiquity-os-marketplace/command-ask@main:
    with:
      model: google/gemini-2.5-flash
      openRouterBaseUrl: https://openrouter.ai/api/v1
      similarityThreshold: 0.9
      maxDepth: 3
  ubiquity-os-marketplace/command-config@main:
    with:
      model: google/gemini-2.5-flash
  ubiquity-os-marketplace/command-query@main:
    with:
      allowPublicQuery: true
  ubiquity-os-marketplace/command-start-stop@main:
    with:
      reviewDelayTolerance: 3 Days
      taskStaleTimeoutDuration: 30 Days
      startRequiresWallet: true
      assignedIssueScope: "org"
      maxConcurrentTasks:
        collaborator: 2
        contributor: 2
      emptyWalletText: Please set your wallet address with the /wallet command first and try again.
      rolesWithReviewAuthority: *teamMembersOnly
      requiredLabelsToStart:
        - name: "Priority: 0 (Regression)"
          allowedRoles: *collaboratorOnly
        - name: "Priority: 1 (Normal)"
          allowedRoles: *collaboratorOnly
        - name: "Priority: 2 (Medium)"
          allowedRoles: *collaboratorOnly
        - name: "Priority: 3 (High)"
          allowedRoles: *collaboratorOnly
        - name: "Priority: 4 (Urgent)"
          allowedRoles: *collaboratorOnly
        - name: "Priority: 5 (Emergency)"
          allowedRoles: *collaboratorOnly
      taskAccessControl:
        usdPriceMax:
          contributor: 1000
          collaborator: Infinity
  ubiquity-os-marketplace/command-wallet@main:
    with:
      registerWalletWithVerification: false
  ubiquity-os-marketplace/daemon-disqualifier@main:
    with:
      warning: 7 days
      pullRequestRequired: true
      eventWhitelist:
        - pull_request.review_requested
        - pull_request.ready_for_review
        - pull_request_review_comment.created
        - issue_comment.created
        - push
      disqualification: 14 days
      prioritySpeed: true
      watch:
        optOut:
          - ubiquibot
          - launch-party
          - staging
          - production
  ubiquity-os-marketplace/daemon-merging@main:
    with:
      approvalsRequired:
        collaborator: 1
        contributor: 2
      mergeTimeout:
        collaborator: 3.5 days
        contributor: 7 days
      repos:
        monitor: []
        ignore:
          - ubiquibot
          - launch-party
          - staging
          - production
      allowedReviewerRoles:
        - COLLABORATOR
        - MEMBER
        - OWNER
  ubiquity-os-marketplace/daemon-pricing@main:
    with:
      labels:
        time: *timeLabels
        priority: *priorityLabels
      basePriceMultiplier: 3
      shouldFundContributorClosedIssue: false
      globalConfigUpdate:
        excludeRepos: []
  ubiquity-os-marketplace/personal-agent-bridge@main:
  ubiquity-os-marketplace/text-conversation-rewards@development:
    with:
      rewards:
        evmNetworkId: 100
        evmPrivateEncrypted: bd5AFnSCO6c5jJyPifpOfr5Zys29RE7SyXkEU3akT13RtGmYDrqGIGuvJQyH53HA5dIba7PL5bXfll0JebmwXYe5gHIXSGX80WuGMDHh0cFfeGjHhmUXe8kkZ1OT2De9qRpqejJcEzdfi-8XNAvP7cQu2Vt-7RNnPw
      incentives:
        requirePriceLabel: true
        limitRewards: true
        collaboratorOnlyPaymentInvocation: true
        contentEvaluator:
          enabled: true
          multipliers:
            - role:
                - ISSUE_SPECIFICATION
              relevance: 1
        externalContent: {}
        userExtractor:
          redeemTask: true
        dataPurge:
          skipCommentsWhileAssigned: "exact"
        formattingEvaluator:
          multipliers:
            - role:
                - ISSUE_AUTHOR
                - PULL_SPECIFICATION
                - ISSUE_COLLABORATOR
                - PULL_COLLABORATOR
              multiplier: 2
              rewards:
                wordValue: 0.1
                html: *tcrHtmlConfig
            - role:
                - ISSUE_SPECIFICATION
              multiplier: 3
              rewards:
                wordValue: 0.1
                html: *tcrHtmlConfig

            - role:
                - ISSUE_CONTRIBUTOR
                - ISSUE_ASSIGNEE
              multiplier: 1
              rewards:
                wordValue: 0.1
                html: *tcrHtmlConfig
            - role:
                - PULL_AUTHOR
                - PULL_CONTRIBUTOR
                - PULL_ASSIGNEE
              multiplier: 0
              rewards:
                wordValue: 0
                html: *tcrHtmlConfig
        permitGeneration: {}
        simplificationIncentivizer: {}
        payment:
          automaticTransferMode: false
        reviewIncentivizer: {}
        githubComment:
          post: true
          debug: false
      dataCollection:
        maxAttempts: 10
        delayMs: 1000
  ubiquity-os-marketplace/text-vector-embeddings@main:
    with:
      dedupeMatchThreshold: 0.95
      dedupeWarningThreshold: 0.8
      matchThreshold: 0.95
      warningThreshold: 0.8
      jobMatchingThreshold: 0.8
      alwaysRecommend: 0
  ubiquity-os-marketplace/daemon-spec-rewriter@main:
    with:
      openRouterAiModel: google/gemini-2.5-flash
      openRouterBaseUrl: https://openrouter.ai/api/v1

  ubiquity-os-marketplace/daemon-xp@main:

  ubiquity-os-marketplace/daemon-planner@main:
    with:
      dryRun: true
      assignedTaskLimit: 2

  ubiquity-os-marketplace/daemon-task-matcher@main:
